
_BUILD = """
load("@wix_incubator_bazelizer//private/ruls/maven:repository.bzl", _go_offline_modules = "maven_repository")

filegroup(
    name = "{maven_dist_name}",
    visibility = ["//visibility:public"],
    srcs = glob(["bin/**", "boot/**", "conf/**", "lib/**"]),
)

_go_offline_modules(
    name = "{go_offline_target_name}",
    visibility = ["//visibility:public"],
    modules = [{go_offline_modules}],
    unsafe_global_settings = "{unsafe_global_settings}"
)

"""

_MVN_RUNNER = """#!/usr/bin/env bash
set -e
{mvn} -s {settings_xml} "$@"
"""

_SETTINGS = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Autogenerated by Basel rule, do not edit. -->
<settings>
    <localRepository>{local_repository}</localRepository>
</settings>
"""

_maven_repository_registry_attrs = {
    "modules": attr.label_list(),
    "use_unsafe_local_cache": attr.bool(default = True),
}

_maven_binary_version = "3.6.3"
_maven_binary_sha256 = "26ad91d751b3a9a53087aefa743f4e16a17741d3915b219cf74112bf87a438c5"
_maven_binary_uri = "https://www2.apache.paket.ua/maven/maven-3/" + _maven_binary_version + "/binaries/apache-maven-" + _maven_binary_version + "-bin.tar.gz"

_maven_dist_name = "maven_%s" % (_maven_binary_version.replace(".", "_"))

def _maven_repository_registry_impl(repository_ctx):
    repository_ctx.download_and_extract(
        url = _maven_binary_uri,
        sha256 = _maven_binary_sha256,
        stripPrefix = "apache-maven-" + _maven_binary_version
    )

    m2_dir = "_m2"
    settings_xml = repository_ctx.path(m2_dir + "/" + "settings.xml")
    local_repository = repository_ctx.path(m2_dir + "/" + "repository")

    repository_ctx.file(
        "BUILD",
        (_BUILD).format(
            maven_dist_name = _maven_dist_name,
            go_offline_target_name = "pinned_maven_repository",
            go_offline_modules = ",".join([
                '"@%s%s"' % (d.workspace_name, d) for d in repository_ctx.attr.modules
            ]),
            unsafe_global_settings = settings_xml
        ),
        False,  # not executable
    )



    repository_ctx.file(
        settings_xml,
        (_SETTINGS).format(
            local_repository = local_repository,
        ),
        False,  # not executable
    )

    mvn = repository_ctx.path("bin/mvn")
    repository_ctx.file(
        "mvn_runner",
        (_MVN_RUNNER).format(
            mvn = mvn,
            settings_xml = settings_xml
        ),
        True,  # executable
    )

maven_repository_registry = repository_rule(
    attrs = _maven_repository_registry_attrs,
    implementation = _maven_repository_registry_impl,
    environ = ["MAVEN_HOME"]
)