


java_library(
    name = "subliby",
    srcs = glob(["*.java"]),
    javacopts = [
        "-source", "8", "-target", "8",
    ],
    deps = [
        "//tests/e2e/lib/src/com/mavenizer/examples/util"
    ],
    visibility = ["//visibility:public"],
)