package tools.jvm.mvn;


import com.google.common.collect.AbstractIterator;
import com.google.common.collect.Iterables;
import com.google.common.collect.Lists;
import com.google.common.io.CharSource;
import com.google.common.io.Closer;
import lombok.SneakyThrows;
import lombok.experimental.UtilityClass;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.compress.archivers.ArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveEntry;
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream;
import org.apache.commons.compress.archivers.tar.TarArchiveOutputStream;
import org.apache.commons.io.FileUtils;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static com.google.common.io.Files.asByteSink;

@UtilityClass
public final class Acts {


    /**
     * Install deps into M2_HOME
     */
    @Slf4j
    static class Deps implements Act {

        @Override
        public Project accept(Project project) {
            Path repo = project.m2Home().resolve("repository");
            project.deps().forEach(dep -> {
                final Path depFolder = dep.relativeTo(repo);
                //noinspection ResultOfMethodCallIgnored
                depFolder.toFile().mkdirs();
                String pref = dep.artifactId() + "-" + dep.version();
                Path jarFile = depFolder.resolve(pref + ".jar");
                copyTo(dep, jarFile);
                String pom =
                        "<project xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://maven.apache.org/POM/4.0.0\" " +
                                "xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd\">\n" +
                        "<modelVersion>4.0.0</modelVersion>\n" +
                        "<groupId>" + dep.groupId() + "</groupId>\n" +
                        "<artifactId>" + dep.artifactId() + "</artifactId>\n" +
                        "<version>" + dep.version() + "</version>\n" +
                        "<description>Pom file generated by " + this.getClass() + "</description>\n" +
                        "</project>";
                Path pomFile = depFolder.resolve(pref + ".pom");
                log.debug("install: {}", dep);
                writeTo(pomFile, pom);
            });
            log.info("Installed deps: {}", Iterables.size(project.deps()));
            return project;
        }

    }

    /**
     * Run maven build.
     */
    private final static class Mvn implements Act {
        private boolean offline;
        private final List<String> args;

        Mvn(boolean offline, String...args) {
            this.offline = offline;
            this.args = Lists.newArrayList(args);
        }

        Mvn( String...args) {
            this(false, args);
        }

        Mvn useOffline() {
            this.offline = true;
            return this;
        }

        @Override
        public Project accept(Project project) {
            final Args args = new Args(project.args());
            if (offline) {
                args.append("--offline");
            }
            this.args.forEach(args::append);
            new BuildMvn().run(new Project.Wrap(project) {
                @Override
                public Args args() {
                    return args;
                }
            });
            return project;
        }
    }

    /**
     * Maven build. Turn off online resolving dependencies.
     */
    static class MvnBuildOffline implements Act {

        @Override
        public Project accept(Project project) {
            return new Mvn( "clean", "package")
                    .useOffline()
                    .accept(project);
        }
    }

    /**
     * Run maven build. Allow to fetch dependencies from the web.
     */
    @Slf4j
    static class MvnGoOffline implements Act {
        @Override
        public Project accept(Project project) {
            log.info("eagerly fetch dependencies to go offline...");
            new Mvn( "dependency:go-offline").accept(project);
            new Mvn( "clean", "package").accept(project);
            return project;
        }
    }

    /**
     * Output.
     */
    static class Outputs implements Act {
        @Override
        public Project accept(Project project) {
            final Path workDir = project.workDir();
            final Path target = workDir.resolve("target").toAbsolutePath();
            project.getOutputs().forEach(name -> {
                Path src = target.resolve(name.src());
                Path dest = Paths.get(name.dest());
                try {
                    Files.copy(src, dest);
                } catch (java.nio.file.NoSuchFileException e) {
                    throw new ToolException("no such file: " + src + ", within: [" + exists(target) + " ...]", e);
                } catch (IOException e) {
                    throw new ToolException(e);
                }

            });
            return project;
        }

        @SneakyThrows
        private String exists(Path target)  {
            return Files.walk(target, 2)
                    .limit(10).map(Path::toString).collect(Collectors.joining(", "));
        }
    }

    @SuppressWarnings("UnstableApiUsage")
    @Slf4j
    static class POM implements Act {

        @Override
        @lombok.SneakyThrows
        public Project accept(Project project) {
            final PomProperties props = pomProperties(project);
            final File syntheticPom = newPomXML(project.workDir().toFile());
            final CharSource renderedTpl = new TemplateEnvelop.Mustache(
                    project.pomXmlTpl(),
                    props
            ).eval();

            renderedTpl.copyTo(asByteSink(syntheticPom).asCharSink(StandardCharsets.UTF_8));
            if (log.isDebugEnabled()) {
                log.debug("\n{}", renderedTpl.read());
            }
            project.args().append("-f", syntheticPom.getAbsolutePath());
            return project;
        }

        interface PomProperties {
            Iterable<Dep> deps();
            String groupId();
            String artifactId();
        }

        private PomProperties pomProperties(Project project) {
            return new PomProperties() {
                @Override
                public Iterable<Dep> deps() {
                    return project.deps();
                }

                @Override
                public String groupId() {
                    return project.groupId();
                }

                @Override
                public String artifactId() {
                    return project.artifactId();
                }
            };
        }

        @lombok.SneakyThrows
        private static File newPomXML(File dir) {
            for (int i = 0; i < 1000; i++) {
                StringBuilder s = new StringBuilder();
                for (int j = 0; j < 10; j++) {
                    s.append((char) ThreadLocalRandom.current().nextInt('a', 'z'));
                }
                File file = new File(dir, "pom-" + s + "-" + i  + ".xml");
                if (!file.exists()) {
                    //noinspection UnstableApiUsage
                    com.google.common.io.Files.touch(file);
                    return file;
                }
            }
            throw new IllegalStateException("random file");
        }
    }


    /**
     * Prepare settings xml.
     */
    @Slf4j
    static class SettingsXml implements Act {

        @Override
        public Project accept(Project project) {
            final Path m2Home = project.m2Home();
            final Path settingsXml = m2Home.resolve("settings.xml").toAbsolutePath();
            final Path repository = m2Home.resolve("repository").toAbsolutePath();
            String xml = "<settings xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd\" xmlns=\"http://maven.apache.org/SETTINGS/1.1.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n" +
                            "<localRepository>" + repository + "</localRepository>\n" +
                            "</settings>";
            save(settingsXml, xml);
            log.debug("\n{}", xml);
            project.args().append("-s", settingsXml.toString());
            return project;
        }

        @lombok.SneakyThrows
        private static void save(Path settingsXml, String xml) {
            Files.write(settingsXml, xml.getBytes(StandardCharsets.UTF_8));
        }
    }


    /**
     * Repository snapshot handler.
     */
    @SuppressWarnings("UnstableApiUsage")
    static class DefRepository implements Act {

        @Override
        @lombok.SneakyThrows
        public Project accept(Project project) {
            final Path tar = project.repoImage();
            final Path dest = project.m2Home().resolve("repository");
            final Closer closer = Closer.create();
            final TarArchiveInputStream ais = closer.register(new TarArchiveInputStream(
                    Files.newInputStream(tar, StandardOpenOption.READ)
            ));
            Iterator<TarArchiveEntry> iter = new AbstractIterator<TarArchiveEntry>() {
                @lombok.SneakyThrows
                @Override
                protected TarArchiveEntry computeNext() {
                    final TarArchiveEntry entry = ais.getNextTarEntry();
                    return entry != null ? entry : endOfData();
                }
            };
            try {
                iter.forEachRemaining(entry -> {
                    if (!ais.canReadEntryData(entry)) return;
                    File file = dest.resolve(entry.getName()).toFile();
                    if (entry.isDirectory()) {
                        defineDirectory(file);
                    } else {
                        defineDirectory(file.getParentFile());
                        copy(ais, file);
                    }
                });
            } finally {
                closer.close();
            }

            return project;
        }

        @lombok.SneakyThrows
        private static void copy(TarArchiveInputStream ais, File file) {
            Files.copy(ais, file.toPath());
        }

        @lombok.SneakyThrows
        private static void defineDirectory(File file) {
            if (!file.isDirectory() && !file.mkdirs())
                throw new IOException("failed to create directory " + file);
        }
    }




    /**
     * Create snapshot from the repository.
     */
    @Slf4j
    static class RepositoryArchiver implements Act {

        @SuppressWarnings("UnstableApiUsage")
        @Override
        @lombok.SneakyThrows
        public Project accept(Project project) {
            final Path m2Home = project.m2Home();
            final Path src = m2Home.resolve("repository");
            final String dest = Iterables.getOnlyElement(project.getOutputs()).src();
            log.debug("Archive: src={} dest={}", src, dest);
            final Closer closer = Closer.create();
            final File destFile = new File(dest);
            final TarArchiveOutputStream aos = closer.register(new TarArchiveOutputStream(
                    asByteSink(destFile).openBufferedStream()
            ));
            aos.setLongFileMode(TarArchiveOutputStream.LONGFILE_POSIX);
            final Stream<Path> walk = Files.walk(src);
            closer.register(walk::close);
            try {
                walk.map(Path::toFile).filter(File::isFile).forEach(file -> writeEntry(src, aos, file));
                aos.finish();
            } finally {
                closer.close();
            }
            log.info("Repository archive created: {}", FileUtils.byteCountToDisplaySize(destFile.length()));
            return project;
        }

        @lombok.SneakyThrows
        private void writeEntry(Path repository, TarArchiveOutputStream aos, File file) {
            final Path filePath = file.toPath();
            final ArchiveEntry entry = aos.createArchiveEntry(file,
                    repository.relativize(filePath).toString());
            aos.putArchiveEntry(entry);
            Files.copy(filePath, aos);
            aos.closeArchiveEntry();
        }
    }


    @Slf4j
    static class Version implements Act {

        @Override
        public Project accept(Project project) {
            log.info("Verify maven version: ");
            new BuildMvn(true).run(new Project.Wrap(project) {
                @Override
                public Args args() {
                    return new Args().append("--version");
                }
            });
            return project;
        }
    }



    @lombok.SneakyThrows
    private static void writeTo(Path pomFile, String pom) {
        java.nio.file.Files.write(pomFile, pom.getBytes(StandardCharsets.UTF_8));
    }

    @lombok.SneakyThrows
    private static void copyTo(Path src, Path jarFile) {
        Files.copy(src, jarFile);
    }

    @lombok.SneakyThrows
    private static void copyTo(Dep dep, Path jarFile) {
        copyTo(dep.source(), jarFile);
    }
}
