package tools.jvm.mvn;

import com.google.common.collect.Lists;
import com.google.common.io.ByteSource;
import com.google.common.io.Files;
import com.jcabi.xml.XML;
import com.jcabi.xml.XMLDocument;
import org.cactoos.text.TextOf;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;

import static org.hamcrest.MatcherAssert.assertThat;

@SuppressWarnings("UnstableApiUsage")
public class ActsTest {

    File tmpWorkDir ;

    @Before
    public void tmp() {
        tmpWorkDir = Files.createTempDir();
    }

    @After
    public void rm() {
        //noinspection ResultOfMethodCallIgnored
        tmpWorkDir.delete();
    }

    @Test
    public void generatePom() throws IOException {
        String pom = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<project>\n" +
                " <!-- xembly:on -->" +
                "    <modelVersion>4.0.0</modelVersion>\n" +
                "    <groupId>BBBB</groupId>\n" +
                "    <artifactId>AAAA</artifactId>\n" +
                "    <version>1.0.0-SNAPSHOT</version>\n" +
                "    <dependencies>\n" +
                "    </dependencies>\n" +
                "</project>";

        Project p = Project.builder()
//                .artifactId("AAAA")
//                .groupId("BBBB")
                .workDir(tmpWorkDir.toPath())
                .pomTemplate(ByteSource.wrap(pom.getBytes()))
                .deps(Lists.newArrayList(new Dep.Simple(null, "xyz", "xyz-aaa", "1.0")))
                .build();

        final Act.Iterative act = new Act.Iterative(
                new Acts.POM()
        );

        final Project accept = act.accept(p);

        XML xml = new XMLDocument(accept.pom().toFile());
        Assert.assertEquals(xml.xpath("//project/groupId/text()").get(0).trim(), "BBBB");
        Assert.assertEquals(xml.xpath("//project/artifactId/text()").get(0).trim(), "AAAA");
        Assert.assertEquals(xml.xpath("//project/dependencies/dependency/groupId/text()"), Lists.newArrayList("xyz"));
        Assert.assertEquals(xml.xpath("//project/dependencies/dependency/artifactId/text()"), Lists.newArrayList("xyz-aaa"));
        Assert.assertEquals(xml.xpath("//project/dependencies/dependency/version/text()"), Lists.newArrayList("1.0"));
    }


    @Test
    public void install() throws IOException {
        final Act.Iterative act = new Act.Iterative(
                new Acts.Deps()
        );
        Path jar = java.nio.file.Files.createTempFile("jar", "jar");

        Files.touch(jar.toFile());
        jar.toFile().deleteOnExit();

        final Project p = Project.builder()
                .workDir(tmpWorkDir.toPath())
                .m2Home(tmpWorkDir.toPath())
                .deps(Lists.newArrayList(
                        new Dep.Simple(jar.toFile(), "xyz.com.baz", "xyz-aaa", "1.0")))
                .build();

        act.accept(p);

        final Path resolve = tmpWorkDir.toPath().resolve("repository/xyz/com/baz/xyz-aaa/1.0/");
        Assert.assertTrue(resolve.resolve("xyz-aaa-1.0.jar").toFile().exists());
        Assert.assertTrue(resolve.resolve("xyz-aaa-1.0.pom").toFile().exists());
    }

    @Test
    public void settings() throws IOException {
        final Act.Iterative act = new Act.Iterative(
                new Acts.SettingsXml(new Repositories.Raw(Collections.singleton(
                        new Repositories.Repository().id("x").url("yyy")
                )))
        );

        final Project p = Project.builder()
                .m2Home(tmpWorkDir.toPath())
                .build();

        act.accept(p);

        final Path xml = p.m2Home().resolve("settings.xml");
        final String xmlStr = new TextOf(xml.toFile()).asString();

        String expected = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<!-- AUTOGENERATED SETTINGS XML FILE. -->\n" +
                "<!-- DO NOT EDIT -->\n" +
                "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\">\n" +
                "\n" +
                "    <localRepository>" + tmpWorkDir.toPath().resolve("repository") + "</localRepository>\n" +
                "\n" +
                "    <profiles>\n" +
                "        <profile>\n" +
                "            <id>bazelizer</id>\n" +
                "            <repositories>\n" +
                "                <repository>\n" +
                "\n" +
                "                    <id>x</id>\n" +
                "                    <name></name>\n" +
                "                    <url>yyy</url>\n" +
                "                </repository>\n" +
                "            </repositories>\n" +
                "            <pluginRepositories>\n" +
                "                <pluginRepository>\n" +
                "                    <id>x</id>\n" +
                "                    <name></name>\n" +
                "                    <url>yyy</url>\n" +
                "                </pluginRepository>\n" +
                "            </pluginRepositories>\n" +
                "        </profile>\n" +
                "    </profiles>\n" +
                "\n" +
                "    <activeProfiles>\n" +
                "        <activeProfile>bazelizer</activeProfile>\n" +
                "    </activeProfiles>\n" +
                "</settings>";
        Assert.assertEquals(expected, xmlStr);
    }
}
