load("//maven:defs.bzl", "declare_module")
load("@maven_e2e_v2//:execute_build.bzl", "execute_build")


#
# API 2.0
#

declare_module(
    name = "module",
    pom_file = ":pom.xml",
    visibility = ["//visibility:public"],
)

